/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.HashMap;
import java.util.Map;
import com.google.gson.JsonObject;

public class App {
    public static void main(String[] args) {
        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("name", "Yana");  // Replace with your name
        jsonObject.addProperty("lastName", "Zukulis");  // Replace with your last name

        System.out.println(jsonObject.toString());
    }
}